version: '3'

services:
  email-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: email-sender
    container_name: email-app
    ports:
      - "3001:3001"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - HTTP_PROXY=http://119.45.19.31:8118
      - HTTPS_PROXY=http://119.45.19.31:8118
      - http_proxy=http://119.45.19.31:8118
      - https_proxy=http://119.45.19.31:8118
      - all_proxy=http://119.45.19.31:8118
      - NO_PROXY=localhost,127.0.0.1
    volumes:
      # 挂载日志目录，方便查看日志
      - ./logs:/app/logs
